// Settings
:idprefix:
:idseparator: -
:component-name: mMec-library
//la valeur de component-name représente la valeur de l'attribut title assigné dans le fichier
//antora.yml
= {component-name}

[#sommaire]
== Sommaire
L’intégration de sources de données pose des défis majeurs en raison des multiples formes d’hétérogénéité qui les caractérisent. Pour y répondre, la médiation constitue une approche pertinente, notamment dans le contexte des Systèmes de Santé Apprenants, où la centralisation est souvent impraticable. Cette thèse propose un procédé systématique d’intégration de sources hétérogènes à une plateforme de médiation dont le modèle est construit à partir d'ontologies.

La contribution principale est la définition d’un procédé d’arrimage structuré autour d’une étape clé : l’individuation des particuliers. L’analyse des méthodes existantes a révélé des défis non résolus, notamment la préservation de la sémantique et la répétabilité, auxquels le procédé proposé entend répondre. Celui-ci est défini à l’aide de la méthode formelle Event-B, qui assure sa rigueur et sa vérifiabilité. Une extension de R2RML, nommée mMEC, a été développée pour formaliser les correspondances entre les structures des sources et le modèle commun dérivé d’une ontologie. Un outil (mmec-cli) a également été conçu pour automatiser l’opérationnalisation de l’arrimage, indépendamment du système de gestion de bases de données utilisé. L’approche a été validée avec plusieurs bases de données médicales, démontrant sa capacité à préserver l’intégrité sémantique et à faciliter l’exploitation des données dans des contextes de recherche rétrospective et de pratique réflexive.

Bien que motivée par les besoins du secteur de la santé, la méthode développée propose un cadre générique pour l’intégration sémantique de sources de données hétérogènes, ouvrant la voie à des applications dans d’autres domaines où l’exploitation harmonisée de données distribuées est essentielle.

:toc:

[#dependances]
== Dépendances
Le projet est développé avec Java 17. Le tableau suivant présente les dépendances du projet.

[cols="1,1,1,1", options="header"]
|===
| Nom | Version | Licence | Lien
| Ontop | 5.3.0 | Apache 2.0 | https://ontop-vkg.org/
| Pilote PostgreSQL | 42.7.4 | BSD 2-Clause | https://jdbc.postgresql.org/
| JOOQ | 3.19.11 | Apache 2.0 | https://github.com/jOOQ/jOOQ/tree/main
| String Template | 4.3.4 | BSD 3-Clause | https://www.stringtemplate.org/
| RDF4J | 4.3.10 | BSD 3-Clause | https://rdf4j.org/
| GRIIS Logger Library | 1.0.3 | Source ouverte - À venir | À venir
| Client JOOQ pour OntoRelCat | 1.0.0 | Source ouverte - À venir  | À venir
|===

[#construction]
== Construction
Le projet est construit avec Gradle.

[source, gradle]
----
./gradlew construction
----

[#utilisation]
== Utilisation

Pour inclure {component-name} dans un autre projet, il faut ajouter la dépendance dans le fichier build.gradle de ce projet, puis rafraichir le projet Gradle.

La *{component-name}* peut être déclarée en utilisant `ca.griis:mMec-library:1.2.0`.

[source, gradle]
----
dependencies {
  implementation "ca.griis:mMec-library:1.2.0"
}
----

Pour développer directement sur la {component-name}, il faut importer le
projet Gradle dans un environnement de développement intégré Java tel qu'Eclipse ou IntelliJ IDEA.
Pour plus de renseignements, consulter la section «{nbsp}<<Construction>>{nbsp}».

[#resultats-analyse-code]
== Résultat des analyses du code source
Plusieurs analyses du code source ont été réalisées pour évaluer la qualité du code, la couverture des tests et la détection de bugs. Les résultats sont présentés dans le tableau ci-dessous.

[cols="1,1,1,1", options="header"]
|===
| Outil | Type | Résultat | Liens

| link:https://pitest.org/[PIT (Pitest)]
| Couverture de code (avec mutation)
| Lignes: 100% +
Mutations: 100% +
Force: 100%
| link:reports/pitest/index.html[Rapport PiTest]

| link:https://www.eclemma.org/jacoco/[JaCoCo]
| Couverture de code
| Instructions: 93% +
Branches: 80% +
| link:reports/jacoco/test/html/index.html[Rapport Jacoco]

| link:https://spotbugs.github.io/[SpotBugs]
| Analyse statique (Détection de bugs)
| Aucun bug détecté
| link:reports/spotbugs/main.html[Rapport Spotbugs]

| link:https://pmd.github.io/[PMD]
| Analyse statique (Qualité du code)
| Aucun bug détecté
| link:reports/pmd/main.html[Rapport PMD]

| link:https://checkstyle.sourceforge.io/[Checkstyle]
| Analyse statique (Style de code)
| Aucune erreur de style détectée
| link:reports/checkstyle/main.html[Rapport Checkstyle]

|===

[#execution-modele]
== Visualisation du modèle d'individuation Event-B
Le modèle de l'algorithme d'individuation a été conçu à l'aide d'Event-B. Les sources, disponibles dans le répertoire `src/main/b-sharp/IndividuationAlgorithm`, peuvent être ouvertes à l’aide de l’environnement de développement https://wp.software.imdea.org/cbc/rodin-installation-and-tips/[Rodin]. Il est nécessaire d'installer les plugins suivants pour le bon fonctionnement du modèle:

. Atelier B provers
. SMT Solvers

De plus, le logiciel https://prob.hhu.de/w/index.php?title=ProB2_JavaFX_UI[ProB 2 UI] peut être utilisé pour visualiser les exemples d'arrimage qui sont disponibles sous: `src/main/b-sharp/IndividuationAlgorithmAnimation`. Voici les étapes à suivre pour lancer une simulation:

. Ouvrir le menu "Rodin Platform" > "Settings"
. Naviguer vers "ProB" > "ProB Standalone"
. Renseigner le champs "location", avec le chemin de l'installation de ProB2UI.
.. Sous MacOS, il s'agit de /Applications/ProB 2 UI.app/Contents/app/prob2-ui-1.2.1-mac-x86_64.jar
. Ouvrir la machine 4-AnimationMachine
. Sélectionner le contexte d'animation désiré sous "SEES"
. Faire un clic droit sur  4-AnimationMachine
. Sélectionner "ProB Standalone..." > "Ouvrir dans ProB Standalone"
. Si tout est installé correctement, ProB2Ui devrait s'ouvrir et la machine devrait s'exécuter. L'initialisation peut prendre quelques minutes
. Il est possible de charger les traces qui sont disponibles dans le répertoire `doc/animation_proB` du présent projet
.. S'assurer de sélectionner la trace correspondant au contexte sélectionné

Une explication de la visualisation ProB des différents cas d'individuation sont disponibles dans le répertoire `doc/animation_proB/visualisation`.

[#execution-tests]
== Exécution des tests
Les tests peuvent être exécutés en utilisant la commande Gradle suivante:
[source, gradle]
----
./gradlew test
----

Les tests d'intégration sont dépendants de l'image Docker `archive.griis.usherbrooke.ca:5004/ontorelcat-ldm:1.0.0-dev`. Pour l'installer :

. Récupérer l'image Docker ontorelcat-ldm.tar.gz à partir de la https://github.com/samdus/mmec-library/releases/download/1.2.0/ontorelcat-ldm.tar.gz[dernière version du projet].
. Charger l'image avec la commande suivante :
[source, shell]
----
docker load < ontorelcat-ldm.tar.gz
----

[#dependance-ontop]
== Dépendance à Ontop
Le projet a été construit avec la version 5.3.0 de Ontop.

Cependant, certaines classes d'Ontop ont dû être adaptées directement. Ces classes ont été copiées depuis le projet Ontop et modifiées pour répondre aux besoins du projet mMEC. Ces classes sont situées sous `src/main/java/it/unibz/inf/ontop`. Il sera nécessaire de vérifier manuellement si ces fichiers doivent être mis à jour lors de la mise à jour de la dépendance à Ontop.

[#licence]
== Copyright et licences

=== Copyright

Copyright 2018-{localyear}, https://www.linkedin.com/in/samueldussault/[Samuel Dussault]

Copyright 2018-{localyear}, https://www.usherbrooke.ca/informatique/nous-joindre/personnel/corps-professoral/professeurs/luc-lavoie[Luc Lavoie]

Copyright 2018-{localyear}, https://www.usherbrooke.ca/recherche/fr/specialistes/details/jean-francois.ethier[Jean-François Ethier]

Copyright 2018-{localyear}, https://www.usherbrooke.ca/informatique/nous-joindre/personnel/corps-professoral/professeurs/christina-khnaisser[Christina Khnaisser]

Copyright 2018-{localyear}, https://griis.ca/[GRIIS]

GRIIS (Groupe de recherche interdisciplinaire en informatique de la santé) +
Faculté des sciences et Faculté de médecine et sciences de la santé +
Université de Sherbrooke (Québec) J1K 2R1 +

CANADA

=== Licences
Le code de ce projet est sous licence link:LiLiQ-R11.txt[LILIQ-R]. Click here for the
link:LILIQ-R11EN.txt[English version].
