== Répertoire de dépendances
Antlr n'a pas de mécanisme de gestion de dépendance particulièrement élaboré. C'est pourquoi nous avons fait le choix de maintenir les dépendances manuellement dans un répertoire séparé. Le présent fichier sert de référence afin de connaître d'où provient chacune des dépendances incluses  dans ce projet.

== Discipulus ; Discipulus_LEX
Grammaire et lexeur définit pour Discipulus. Ne corresponds pas actuellement à une version réelle de Discipulus.

=== IRI_LEX
Il s'agit d'une approximation de la grammaire définie par la https://datatracker.ietf.org/doc/html/rfc3987[RFC 3987 (IRI)].

=== LEX
Il s'agit du lexeur de base utilisé au GRIIS. Le fichier provient du projet https://depot.griis.usherbrooke.ca/USoutien/dadagem/odmv2/-/tree/v0.3.4/src/main/antlr/ca/griis/odmv2[ODMv2, tag: v0.3.4].

=== MicroOnto, MOnto_LEX
Grammaire et lexeur définient pour MicroOnto. Le fichier provient du projet https://depot.griis.usherbrooke.ca/arot/hephaistos/MOnto/-/tree/b22ff75e4d608199ed13a816e85845ec9a566d59/src/main/antlr/ca/griis/monto/microonto[MOnto selon le commit b22ff75e4d608199ed13a816e85845ec9a566d59].

== mRel, mRel_LEX
Grammaire et lexeur définient pour l'OntoRel. Les fichiers ne sont que temporaire, en attendant leur extraction d'OntoRelA.
